#!/bin/bash
# Script to help upload Windows executable to release

echo "Manual Windows Build Instructions:"
echo "=================================="
echo ""
echo "Since the CI/CD pipeline is having issues, you can manually build and upload the Windows executable:"
echo ""
echo "1. On a Windows machine:"
echo "   - Clone the repository"
echo "   - Install Python 3.11"
echo "   - Run: pip install pyinstaller pillow requests aiohttp websockets pydantic"
echo "   - Run: python build_windows.py"
echo "   - This creates dist/BloodClockTowerAI/ folder"
echo ""
echo "2. Create a ZIP file:"
echo "   - Right-click on dist/BloodClockTowerAI/ folder"
echo "   - Send to > Compressed (zipped) folder"
echo "   - Name it: BloodClockTowerAI-Windows.zip"
echo ""
echo "3. Upload to GitHub release:"
echo "   - Go to: https://github.com/emmjayh/ProjectClocktower/releases/tag/v1.0.2"
echo "   - Click 'Edit release' (pencil icon)"
echo "   - Drag and drop BloodClockTowerAI-Windows.zip into the assets area"
echo "   - Click 'Update release'"
echo ""
echo "Alternatively, if you have the ZIP file locally, run:"
echo "gh release upload v1.0.2 BloodClockTowerAI-Windows.zip --clobber"