name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install only core dependencies, skip heavy ML packages for CI
        pip install requests aiohttp websockets pydantic pillow pyinstaller
        
    - name: Build Windows executable
      run: |
        python build_windows.py
        
    - name: Create ZIP of Windows executable
      run: |
        cd dist
        # Use PowerShell's Compress-Archive for Windows
        Compress-Archive -Path "BloodClockTowerAI" -DestinationPath "BloodClockTowerAI-Windows.zip"
        
    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/BloodClockTowerAI-Windows.zip
        retention-days: 30

  create-release:
    runs-on: ubuntu-latest
    needs: build-windows
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Windows build
      uses: actions/download-artifact@v4
      with:
        name: windows-executable
        path: dist/
        
    - name: Create Release with Windows executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Blood on the Clocktower AI Storyteller ${{ github.ref_name }}" \
          --notes "## Blood on the Clocktower AI Storyteller ${{ github.ref_name }}
        
        ### 🎭 Features:
        - Full AI Storyteller for Blood on the Clocktower
        - Voice interaction with speech recognition and TTS
        - Enhanced botc.app platform integration
        - Complete Trouble Brewing script support
        - Intelligent decision making for character abilities
        - Real-time game state management
        
        ### 🆕 What's New in ${{ github.ref_name }}:
        - **Enhanced botc.app Compatibility**: Added specialized BotCAppAdapter for seamless integration
        - **Improved Connection Handling**: WebSocket with HTTP polling fallback
        - **Better Error Recovery**: Robust handling of connection failures
        - **Windows Build Fixes**: Resolved Unicode encoding and PyInstaller dependency issues
        - **Code Quality**: Fixed all Black, isort, and flake8 formatting issues
        
        ### 🔧 Installation:
        **Windows Users:**
        1. Download \`BloodClockTowerAI-Windows.zip\`
        2. Extract to a folder
        3. Run \`download_models.bat\` first to download AI models
        4. Run \`BloodClockTowerAI.exe\`
        
        **Developers:**
        \`\`\`bash
        git clone https://github.com/emmjayh/ProjectClocktower.git
        cd ProjectClocktower
        pip install -r requirements.txt
        python -m src.gui.main_window
        \`\`\`
        
        ### 🎯 System Requirements:
        - Windows 10/11 (for executable)
        - Python 3.11 or 3.12 (for source)
        - Microphone for voice commands (optional)
        - Speakers/headphones for AI narration (optional)
        - Internet connection for platform integration" \
          dist/BloodClockTowerAI-Windows.zip